### ISSUE TITLE
Testing code in events

### ISSUE THREAD

**Issue by damirarh** [js-data/js-data-angular-mocks#12]
Is it possible to test code that is executed in events, e.g. `DS.afterInject`?

I tried adding the following test case to `test.js` from the repository:

```
describe('events', function() {
  var DS;
  var User;

  beforeEach(inject(function (_DS_, _User_) {
    DS = _DS_;
    User = _User_;
  }));

  it('should invoke events', function(done) {
    User.on('DS.afterInject', function(resource, user) {
      user.handled = true;
    });

    User.expectRefreshAll()
      .respond([{name: 'Sally',id: 4}]);

    User.refreshAll()
      .then(function(users) {
        assert.deepEqual(users, [{name: 'Sally',id: 4}]); // this succeeds
        // the following fails, because the event hasn't been executed, yet.
        // assert.deepEqual(users, [{name: 'Sally',id: 4, handled: true}]);
        done();
      });

    DS.flush();
  });
});
```

Since the events are triggered asynchronously, I assume another call to `$rootScope.$digest()` is required, but from what I tried, it either had no effect or got a `[$rootScope:inprog] $digest already in progress` error.

How could I structure the test to assert the results of the code executed in `DA.afterInject` or another event?

**Comment by damirarh** [comment]
I realized events are not triggered at all when using `js-data-angular-mocks`. However, they can be tested without using it by directly calling the method that triggers them, e.g `DS.inject()` for `DS.afterInject` event. This way no request to external data sources will be made, which would require mocking in the first place. This could be a working test for my scenario above:

```
describe('events', function() {
    var User;
    var $rootScope;

    beforeEach(function () {
        inject(function (_User_, _$rootScope_) {
            User = _User_;
            $rootScope = _$rootScope_;
        })
    });

    it('are only called when methods are not mocked', function() {
        User.on('DS.afterInject', function(resource, user) {
            user.handled = true;
        });

        var user = User.inject({id: 1, username: 'damir'});

        expect(user.handled).toBe(true);
    });
});
```
I've written [a blog post](http://www.damirscorner.com/blog/posts/20151220-UnitTestingJsdataCodeInAngularServices.html) with more details about this and everything else I've learned in the past week about unit testing JSData code.

**Comment by jmdobry** [comment]
Sorry I didn't respond sooner. Your solution is what I would have suggested.
